import { useState } from 'react'
import { collection, addDoc, serverTimestamp } from 'firebase/firestore'
import { db } from '../firebase'
import { STUDENT_FORM, MENTOR_FORM, submitToGoogleForm } from '../googleFormsConfig'

const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY

// ── Gemini API call ──────────────────────────────────────────────────────────
async function callGemini(org, need) {
  const prompt = `You are a requirements analyst for MpowerNPO, where student developers build tech solutions for nonprofits.

Organization: ${org}
IT Need: ${need}

Return ONLY a valid JSON object with exactly these 3 keys — keep each value short and clear:
{
  "summary": "1-2 sentence plain-English restatement of what they need",
  "solution": "1-2 sentence description of what will be built to solve it",
  "impact": "One concrete sentence on how this helps the nonprofit"
}
No extra keys, no markdown, just the JSON object.`

  const res = await fetch(
    `https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent?key=${GEMINI_API_KEY}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: { temperature: 0.4, maxOutputTokens: 4096 },
      }),
    }
  )

  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    throw new Error(err?.error?.message || `API error (status ${res.status})`)
  }

  const data = await res.json()
  const candidate = data.candidates?.[0]
  if (!candidate) throw new Error('No candidate in response')
  const text = candidate.content?.parts?.[0]?.text?.trim() || ''
  const start = text.indexOf('{')
  const end = text.lastIndexOf('}')
  if (start === -1 || end === -1) throw new Error('No JSON found in AI response. Raw: ' + text.slice(0, 200))
  return JSON.parse(text.slice(start, end + 1))
}

function buildEmailBody(form, report) {
  return [
    'MpowerNPO — IT Requirements Report',
    '=====================================',
    `Organization: ${form.org}`,
    `Contact: ${form.name}`,
    `Email: ${form.email}`,
    '',
    'ORIGINAL IT NEED',
    '----------------',
    form.need,
    '',
    'AI-GENERATED REPORT',
    '--------------------',
    '',
    'WHAT YOU NEED',
    report.summary,
    '',
    "WHAT WE'LL BUILD",
    report.solution,
    '',
    'EXPECTED IMPACT',
    report.impact,
    '',
    '=====================================',
    'Generated by MpowerNPO AI System',
    'askmpowernpo@gmail.com | Johnston, Iowa',
  ].join('\n')
}

// ── Remove old EmailJS helper (replaced by Google Forms) ─────────────────────

// ── Hidden skill scoring (not shown to applicant) ────────────────────────────
function calcSkillScore(form) {
  let score = 0
  const expMap = { never: 0, lt6mo: 1, '6to12mo': 2, '1to2yr': 3, '2plusyr': 4 }
  score += expMap[form.experience] || 0
  score += Math.min((form.skills || []).length, 5)
  if (form.hasPrevProjects === 'yes') score += 2
  const descLen = (form.projectDesc || '').trim().length
  if (descLen > 300) score += 3
  else if (descLen > 150) score += 2
  else if (descLen > 50) score += 1
  if (form.usesGit === 'yes') score += 2
  const hoursMap = { '1to3': 1, '3to5': 2, '5to10': 3, '10plus': 4 }
  score += hoursMap[form.hoursPerWeek] || 0
  const level = score >= 12 ? 'advanced' : score >= 6 ? 'intermediate' : 'beginner'
  return { score, level }
}


// ── Nonprofit Form ────────────────────────────────────────────────────────────
function NonprofitForm() {
  const [form, setForm] = useState({ org: '', name: '', email: '', need: '' })
  const [stage, setStage] = useState('form')
  const [report, setReport] = useState(null)
  const [error, setError] = useState('')

  const set = (field) => (e) => setForm(f => ({ ...f, [field]: e.target.value }))

  const handleSubmit = async () => {
    if (!form.org || !form.name || !form.email || !form.need) {
      setError('Please fill in all fields before submitting.')
      return
    }
    if (!GEMINI_API_KEY || GEMINI_API_KEY === 'your_gemini_api_key_here') {
      setError('Gemini API key not configured. Add your key to the .env file.')
      return
    }
    setError('')
    setStage('loading')
    try {
      const r = await callGemini(form.org, form.need)
      setReport(r)
      setStage('report')
    } catch (err) {
      setError(`Error: ${err.message}. Please try again.`)
      setStage('form')
    }
  }

  const handleApprove = () => {
    // Save request to Firestore so admin/mentor can assign it
    if (db) {
      addDoc(collection(db, 'nonprofitRequests'), {
        org: form.org,
        contactName: form.name,
        email: form.email,
        need: form.need,
        aiReport: report,
        status: 'new',
        submittedAt: serverTimestamp(),
      }).catch(err => console.error('Failed to save request:', err))
    }
    setStage('confirmed')
  }
  const handleRedo = () => { setStage('form'); setReport(null) }

  if (stage === 'loading') {
    return (
      <div className="cpanel">
        <div className="ai-loading">
          <div className="ai-spinner" />
          <p>Analyzing your IT need with AI…</p>
          <p style={{ fontSize: '0.75rem', marginTop: '0.2rem' }}>Generating your requirements report</p>
        </div>
      </div>
    )
  }

  if (stage === 'report' && report) {
    return (
      <div className="ai-report">
        <div className="ai-report-header">
          <span className="ai-report-badge">AI Report</span>
          <span className="ai-report-title">{form.org}</span>
        </div>
        <div className="ai-section">
          <div className="ai-section-label">What You Need</div>
          <div className="ai-section-text">{report.summary}</div>
        </div>
        <div className="ai-section">
          <div className="ai-section-label">What We'll Build</div>
          <div className="ai-section-text">{report.solution}</div>
        </div>
        <div className="ai-section">
          <div className="ai-section-label">Expected Impact</div>
          <div className="ai-section-text">{report.impact}</div>
        </div>
        <div className="ai-actions">
          <div className="ai-actions-label">Does this accurately capture your IT need?</div>
          <div className="ai-btn-row">
            <button className="ai-btn-yes" onClick={handleApprove}>✅ Yes, looks accurate</button>
            <button className="ai-btn-no" onClick={handleRedo}>✏️ No, let me revise</button>
          </div>
        </div>
      </div>
    )
  }

  if (stage === 'confirmed' && report) {
    const body = buildEmailBody(form, report)
    const hrefSelf = `mailto:${encodeURIComponent(form.email)}?subject=${encodeURIComponent('MpowerNPO — Your IT Requirements Report')}&body=${encodeURIComponent(body)}`
    const hrefUs   = `mailto:askmpowernpo@gmail.com?subject=${encodeURIComponent('Nonprofit IT Request: ' + form.org)}&body=${encodeURIComponent(body)}`
    return (
      <div className="cpanel">
        <div className="fsuccess">
          <span>✅</span>
          <p>Request Received!</p>
          <small>We've received your IT request for <strong>{form.org}</strong>. Our team will review it and reach out soon. — The MpowerNPO Team</small>
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.6rem', marginTop: '0.25rem' }}>
          <p style={{ fontSize: '0.75rem', color: 'var(--muted)', textAlign: 'center' }}>Want a copy of your requirements report?</p>
          <a className="ai-btn-email self" href={hrefSelf}>📧 Email me a copy of the report</a>
          <a className="ai-btn-email us" href={hrefUs}>📤 Also send it directly to MpowerNPO</a>
        </div>
      </div>
    )
  }

  return (
    <div className="cpanel">
      <div className="fg">
        <label>Organization Name</label>
        <input type="text" placeholder="e.g. Des Moines Food Bank" value={form.org} onChange={set('org')} />
      </div>
      <div className="fg">
        <label>Contact Name</label>
        <input type="text" placeholder="Your name" value={form.name} onChange={set('name')} />
      </div>
      <div className="fg">
        <label>Email Address</label>
        <input type="email" placeholder="you@organization.org" value={form.email} onChange={set('email')} />
      </div>
      <div className="fg">
        <label>Describe Your IT Need</label>
        <textarea rows={4} placeholder="e.g. We track volunteers in a spreadsheet and it takes hours. We need a better system." value={form.need} onChange={set('need')} />
      </div>
      <button className="btn" style={{ width: '100%', border: 'none' }} onClick={handleSubmit}>
        Submit IT Request →
      </button>
      {error && <p className="ai-error">{error}</p>}
    </div>
  )
}

// ── Student Form ──────────────────────────────────────────────────────────────
function StudentForm() {
  const [form, setForm] = useState({
    name: '',
    school: '',
    email: '',
    skills: [],
    motivation: '',
    experience: '',
    hasPrevProjects: '',
    projectDesc: '',
    usesGit: '',
    projectTypes: [],
    hoursPerWeek: '',
  })
  const [done, setDone] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState('')

  const setField = (field) => (e) => setForm(f => ({ ...f, [field]: e.target.value }))

  const toggleSkill = (skill) => setForm(f => ({
    ...f,
    skills: f.skills.includes(skill) ? f.skills.filter(s => s !== skill) : [...f.skills, skill],
  }))

  const toggleProjectType = (type) => setForm(f => ({
    ...f,
    projectTypes: f.projectTypes.includes(type) ? f.projectTypes.filter(t => t !== type) : [...f.projectTypes, type],
  }))

  const handleSubmit = async () => {
    if (!form.name || !form.email || !form.school || !form.motivation || !form.experience || !form.hoursPerWeek) {
      setError('Please fill in all required fields (marked with *).')
      return
    }
    setError('')
    setSubmitting(true)

    const { score, level } = calcSkillScore(form)

    // Save to Firestore (admin-accessible)
    try {
      if (db) {
        await addDoc(collection(db, 'applications'), {
          type: 'youth',
          name: form.name,
          email: form.email,
          school: form.school,
          skills: form.skills,
          motivation: form.motivation,
          experience: form.experience,
          hasPrevProjects: form.hasPrevProjects,
          projectDesc: form.projectDesc,
          usesGit: form.usesGit,
          projectTypes: form.projectTypes,
          hoursPerWeek: form.hoursPerWeek,
          skillScore: score,
          skillLevel: level,
          submittedAt: serverTimestamp(),
          status: 'pending',
        })
      }
    } catch (err) {
      console.error('Firestore save failed:', err)
    }

    // Submit to Google Form (goes into your Google Sheet)
    submitToGoogleForm(STUDENT_FORM, {
      name: form.name,
      school: form.school,
      email: form.email,
      skills: form.skills,
      experience: form.experience,
      hasPrevProjects: form.hasPrevProjects,
      projectDesc: form.projectDesc,
      usesGit: form.usesGit,
      projectTypes: form.projectTypes,
      hoursPerWeek: form.hoursPerWeek,
      motivation: form.motivation,
    })

    setSubmitting(false)
    setDone(true)
  }

  if (done) return (
    <div className="cpanel">
      <div className="fsuccess">
        <span>✅</span>
        <p>Application submitted!</p>
        <small>We'll review your application and email you login credentials when you're accepted. — The MpowerNPO Team</small>
      </div>
    </div>
  )

  return (
    <div className="cpanel">
      <div className="fg">
        <label>Full Name *</label>
        <input type="text" placeholder="Your name" value={form.name} onChange={setField('name')} />
      </div>
      <div className="fg">
        <label>School &amp; Grade *</label>
        <input type="text" placeholder="e.g. Johnston Middle School, 9th Grade" value={form.school} onChange={setField('school')} />
      </div>
      <div className="fg">
        <label>Email Address *</label>
        <input type="email" placeholder="you@school.edu" value={form.email} onChange={setField('email')} />
      </div>
      <div className="fg">
        <label>Your Coding Skills</label>
        <div className="cbs">
          {['Python', 'JavaScript', 'React', 'SQL / Databases', 'HTML / CSS', 'Java', 'C / C++', 'Other'].map(s => (
            <label className="cb" key={s}>
              <input type="checkbox" checked={form.skills.includes(s)} onChange={() => toggleSkill(s)} /> {s}
            </label>
          ))}
        </div>
      </div>
      <div className="fg">
        <label>How long have you been coding? *</label>
        <select value={form.experience} onChange={setField('experience')}>
          <option value="">Select one…</option>
          <option value="never">I'm just starting out / never coded before</option>
          <option value="lt6mo">Less than 6 months</option>
          <option value="6to12mo">6–12 months</option>
          <option value="1to2yr">1–2 years</option>
          <option value="2plusyr">More than 2 years</option>
        </select>
      </div>
      <div className="fg">
        <label>Have you worked on any coding projects before?</label>
        <div className="cbs">
          {[{ val: 'yes', lbl: 'Yes' }, { val: 'no', lbl: 'No, this would be my first' }].map(o => (
            <label className="cb" key={o.val}>
              <input type="radio" name="hasPrevProjects" value={o.val} checked={form.hasPrevProjects === o.val} onChange={setField('hasPrevProjects')} /> {o.lbl}
            </label>
          ))}
        </div>
      </div>
      {form.hasPrevProjects === 'yes' && (
        <div className="fg">
          <label>Tell us about your coolest or most challenging project</label>
          <textarea rows={3} placeholder="What did you build? What technologies did you use? What was the hardest part?" value={form.projectDesc} onChange={setField('projectDesc')} />
        </div>
      )}
      <div className="fg">
        <label>Do you use Git or GitHub?</label>
        <div className="cbs">
          {[{ val: 'yes', lbl: 'Yes' }, { val: 'no', lbl: 'No / Not yet' }].map(o => (
            <label className="cb" key={o.val}>
              <input type="radio" name="usesGit" value={o.val} checked={form.usesGit === o.val} onChange={setField('usesGit')} /> {o.lbl}
            </label>
          ))}
        </div>
      </div>
      <div className="fg">
        <label>What kind of projects excite you most?</label>
        <div className="cbs">
          {['Websites & Web Apps', 'Mobile Apps', 'Data & Analytics', 'Automation', 'AI / Machine Learning', 'Games', 'Other'].map(t => (
            <label className="cb" key={t}>
              <input type="checkbox" checked={form.projectTypes.includes(t)} onChange={() => toggleProjectType(t)} /> {t}
            </label>
          ))}
        </div>
      </div>
      <div className="fg">
        <label>How many hours per week can you dedicate? *</label>
        <select value={form.hoursPerWeek} onChange={setField('hoursPerWeek')}>
          <option value="">Select one…</option>
          <option value="1to3">1–3 hours</option>
          <option value="3to5">3–5 hours</option>
          <option value="5to10">5–10 hours</option>
          <option value="10plus">10+ hours</option>
        </select>
      </div>
      <div className="fg">
        <label>Why do you want to join MpowerNPO? *</label>
        <textarea rows={3} placeholder="Tell us what drives you and what you hope to gain or contribute…" value={form.motivation} onChange={setField('motivation')} />
      </div>
      <button className="btn" style={{ width: '100%', border: 'none' }} onClick={handleSubmit} disabled={submitting}>
        {submitting ? 'Submitting…' : 'Apply to Join →'}
      </button>
      {error && <p className="ai-error">{error}</p>}
    </div>
  )
}

// ── Mentor Form ───────────────────────────────────────────────────────────────
function MentorForm() {
  const [form, setForm] = useState({
    name: '',
    background: '',
    email: '',
    expertise: [],
    hoursPerMonth: '',
    hasMentoredBefore: '',
    linkedIn: '',
    motivation: '',
  })
  const [done, setDone] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState('')

  const setField = (field) => (e) => setForm(f => ({ ...f, [field]: e.target.value }))
  const toggleExpertise = (area) => setForm(f => ({
    ...f,
    expertise: f.expertise.includes(area) ? f.expertise.filter(a => a !== area) : [...f.expertise, area],
  }))

  const handleSubmit = async () => {
    if (!form.name || !form.email || !form.background || !form.hoursPerMonth) {
      setError('Please fill in all required fields (marked with *).')
      return
    }
    setError('')
    setSubmitting(true)

    // Save to Firestore
    try {
      if (db) {
        await addDoc(collection(db, 'applications'), {
          type: 'mentor',
          name: form.name,
          email: form.email,
          background: form.background,
          expertise: form.expertise,
          hoursPerMonth: form.hoursPerMonth,
          hasMentoredBefore: form.hasMentoredBefore,
          linkedIn: form.linkedIn,
          motivation: form.motivation,
          submittedAt: serverTimestamp(),
          status: 'pending',
        })
      }
    } catch (err) {
      console.error('Firestore save failed:', err)
    }

    // Submit to Google Form (goes into your Google Sheet)
    submitToGoogleForm(MENTOR_FORM, {
      name: form.name,
      background: form.background,
      email: form.email,
      linkedIn: form.linkedIn,
      expertise: form.expertise,
      hoursPerMonth: form.hoursPerMonth,
      hasMentoredBefore: form.hasMentoredBefore,
      motivation: form.motivation,
    })

    setSubmitting(false)
    setDone(true)
  }

  if (done) return (
    <div className="cpanel">
      <div className="fsuccess">
        <span>✅</span>
        <p>Application submitted!</p>
        <small>We'll review your application and be in touch soon. — The MpowerNPO Team</small>
      </div>
    </div>
  )

  return (
    <div className="cpanel">
      <div className="fg">
        <label>Full Name *</label>
        <input type="text" placeholder="Your name" value={form.name} onChange={setField('name')} />
      </div>
      <div className="fg">
        <label>Professional Background *</label>
        <input type="text" placeholder="e.g. Software Engineer, 8 years exp." value={form.background} onChange={setField('background')} />
      </div>
      <div className="fg">
        <label>Email Address *</label>
        <input type="email" placeholder="you@company.com" value={form.email} onChange={setField('email')} />
      </div>
      <div className="fg">
        <label>LinkedIn or Portfolio URL (optional)</label>
        <input type="url" placeholder="https://linkedin.com/in/yourname" value={form.linkedIn} onChange={setField('linkedIn')} />
      </div>
      <div className="fg">
        <label>Areas of Expertise</label>
        <div className="cbs">
          {['Web Development', 'Data & Analytics', 'Project Management', 'AI & Automation', 'UI/UX Design', 'Mobile Development', 'Cybersecurity', 'Cloud / DevOps'].map(s => (
            <label className="cb" key={s}>
              <input type="checkbox" checked={form.expertise.includes(s)} onChange={() => toggleExpertise(s)} /> {s}
            </label>
          ))}
        </div>
      </div>
      <div className="fg">
        <label>Hours available per month *</label>
        <input type="text" placeholder="e.g. 4–6 hours" value={form.hoursPerMonth} onChange={setField('hoursPerMonth')} />
      </div>
      <div className="fg">
        <label>Have you mentored students before?</label>
        <div className="cbs">
          {[{ val: 'yes', lbl: 'Yes' }, { val: 'no', lbl: 'No, but I\'m excited to start' }].map(o => (
            <label className="cb" key={o.val}>
              <input type="radio" name="hasMentoredBefore" value={o.val} checked={form.hasMentoredBefore === o.val} onChange={setField('hasMentoredBefore')} /> {o.lbl}
            </label>
          ))}
        </div>
      </div>
      <div className="fg">
        <label>Why do you want to mentor with MpowerNPO? (optional)</label>
        <textarea rows={3} placeholder="Tell us what motivates you to give back…" value={form.motivation} onChange={setField('motivation')} />
      </div>
      <button className="btn" style={{ width: '100%', border: 'none' }} onClick={handleSubmit} disabled={submitting}>
        {submitting ? 'Submitting…' : 'Volunteer as Mentor →'}
      </button>
      {error && <p className="ai-error">{error}</p>}
    </div>
  )
}

// ── Main Contact Section ──────────────────────────────────────────────────────
export default function Contact() {
  const [tab, setTab] = useState('nonprofit')

  return (
    <section id="contact">
      <div className="inner">
        <span className="slabel">Get In Touch</span>
        <h2 className="stitle">Submit a <em>Request</em><br />or join our team</h2>
        <p className="ssub">Whether you're a nonprofit with an IT need or a student ready to build something that matters — fill out the form and we'll be in touch.</p>
        <div className="cgrid">
          <div className="cform">
            <div className="ctabs">
              <button className={`ctab${tab === 'nonprofit' ? ' on' : ''}`} onClick={() => setTab('nonprofit')}>I'm a Nonprofit</button>
              <button className={`ctab${tab === 'student' ? ' on' : ''}`} onClick={() => setTab('student')}>I'm a Student</button>
              <button className={`ctab${tab === 'mentor' ? ' on' : ''}`} onClick={() => setTab('mentor')}>I'm a Mentor</button>
            </div>
            {tab === 'nonprofit' && <NonprofitForm />}
            {tab === 'student'   && <StudentForm />}
            {tab === 'mentor'    && <MentorForm />}
          </div>
          <div className="cinfo">
            <div className="cicard">
              <div className="ciico">✉️</div>
              <div>
                <div className="cilbl">Email Us</div>
                <div className="cival">askmpowernpo@gmail.com</div>
              </div>
            </div>
            <div className="cicard">
              <div className="ciico">📍</div>
              <div>
                <div className="cilbl">Based In</div>
                <div className="cival">Johnston, Iowa</div>
              </div>
            </div>
            <div className="cquote">
              <p>"Technology education should be applied, responsible, and measurable. MpowerNPO is designed to make that possible."</p>
              <small>— Mayank Bhatt, Founder &amp; Youth Leader</small>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
